### ISSUE TITLE
Implement `->` operator

### ISSUE THREAD

**Issue by Nutomic** [PPakalns/diesel_json#1]
It looks like you just created this project, and its perfect timing for me as I need a way to query json data. The only thing missing for that is support for the `->` operator in postgres, to allow filtering data based on specific fields in the json data. Do you have any plans to add that?

Example from the [postgres docs](https://www.postgresql.org/docs/9.4/functions-json.html):

Query: `'{"a": {"b":"foo"}}'::json->'a'`

Result: `{"b":"foo"}`

**Comment by PPakalns** [comment]
Hi! Thanks for checking out this library.

For now planned scope is to only provide wrapper type that hides implementation details and provides very simple interface for object serialization to, de-serialization from database json, jsonb values.

For now, to use such query in diesel you can use [sql_query](https://docs.diesel.rs/diesel/fn.sql_query.html). There could be other ways too like extending diesel with adding your own expressions.

For implementing type safe "->" json operator, it would require some kind of similar "dsl" schema definition approach for jsonb structure fields as is done now for database schema in diesel. Of course the schema could be generated by procedural macro from type, but for now it is out of the scope of planned features for this library. 

Will give notification if something changes :)

**Comment by PPakalns** [comment]
Small note, operator "->" is partially supported. The returned data can still be parsed with `diesel_json::Json`.

If you have query like this: `'{"a": {"b":"foo"}}'::jsonb->'a'`

And you only need support for retrieving and parsing the returned data. You can do something like this.

```rust
    #[derive(Serialize, Deserialize, Debug)]
    struct MyStruct {
        b: String
    }
    #[derive(QueryableByName, Debug)]
    struct SelectLayout {
        #[sql_type = "diesel::sql_types::Jsonb"]
        data: diesel_json::Json<MyStruct>
    }

    let result: Vec<SelectLayout> = sql_query(r#"SELECT '{"a": {"b":"foo"}}'::jsonb->'a' as data"#).load(&connection).unwrap();
```

**Comment by Nutomic** [comment]
Actually the snippet above was just an example from the postgres docs. My actual query is more complicated, and I noticed while testing that it also needs the `->>` operator. So the raw query you suggested is probably the best option, thanks a lot for that!
